---
# Scan Role Metadata

galaxy_info:
  role_name: scan
  author: Roger Lopez
  description: Run compliance scans on Windows VMs using DISA SCC
  company: ""
  license: Apache-2.0
  min_ansible_version: "2.14"

  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - compliance
    - stig
    - scanning
    - scap

dependencies: []
