---
# Remediate Role Metadata

galaxy_info:
  role_name: remediate
  author: Roger Lopez
  description: Dispatch compliance remediation to OS-specific roles
  company: ""
  license: Apache-2.0
  min_ansible_version: "2.14"

  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"

  galaxy_tags:
    - windows
    - compliance
    - stig
    - remediation
    - hardening

dependencies: []
