---
# Remediate Role - Handlers
# Handlers needed by included STIG remediation tasks

- name: restart lanmanserver
  ansible.windows.win_service:
    name: LanmanServer
    state: restarted
    force_dependent_services: true

- name: restart lanmanworkstation
  ansible.windows.win_service:
    name: LanmanWorkstation
    state: restarted
    force_dependent_services: true

- name: restart wuauserv
  ansible.windows.win_service:
    name: wuauserv
    state: restarted

- name: restart winrm
  ansible.windows.win_service:
    name: WinRM
    state: restarted

- name: gpupdate
  ansible.windows.win_shell: gpupdate /force
